#!/bin/bash
log_file="$1"
cat "$log_file" | wc | awk 'BEGIN{printf "Requests_amount\n"}{print $1}' > request_amount.csv
awk 'length($6) < 6 {print substr($6, 2)}' "$log_file" | sort | uniq -c | sort -r -nk1 | awk 'BEGIN{printf "Request_type Amount\n"}{print $2, $1}' > requests_by_type.csv
awk '{print $7}' "$log_file" | sort | uniq -c | sort -r -nk1 | awk 'BEGIN{printf "Url Number_of_requests\n"}{print $2, $1} NR==10{exit}' > top10_most_frequent.csv
awk '$9 ~ /^5/ {print $1}' "$log_file" | sort | uniq -c | sort -r -nk1 | awk 'BEGIN{printf "IP Number_of_requests\n"} {print $2, $1} NR==5{exit}' > top5_5xx_err.csv
awk '$9 ~ /^4/ {print $7, $9, $1}' "$log_file" | sort -uk1 | awk '{print $1, $2, length($1), $3}' | sort -r -nk3 | awk 'BEGIN{printf "Url Status_code Url_size IP\n"} {print} NR==5{exit}'\
> top5_4xx_err.csv
